/* Automatically generated by fftw-wisdom-to-conf from fftw 3.3.10.
   DO NOT EDIT!  (Unless you really, really want to.  Then it's okay.) */
#define DECLARE(name) extern void name(void *);
#define STRINGIZEx(x) #x
#define STRINGIZE(x) STRINGIZEx(x)
#define SOLVTAB(s) { s, STRINGIZE(s) },
void fftwf_configure_planner(void *plnr)
{
    struct solvtab_s { void (*reg)(void *); const char *reg_nam; };
    extern void fftwf_solvtab_exec(const struct solvtab_s s[], void *);

#define DO(X) \
    X(fftwf_codelet_n1bv_128_neon)\
    X(fftwf_codelet_n1fv_128_neon)\
    X(fftwf_codelet_t3bv_16_neon)\
    X(fftwf_codelet_t3fv_16_neon)\
    X(fftwf_dft_buffered_register)\
    X(fftwf_dft_nop_register)\
    X(fftwf_dft_r2hc_register)\
    X(fftwf_rdft_rank0_register)\
    /* end DO(X) */

    DO(DECLARE)

    const struct solvtab_s s[] = {
        DO(SOLVTAB)
        { 0, 0 }
    };

    fftwf_solvtab_exec(s, plnr);
#undef DO
}

/* Automatically generated by fftw-wisdom-to-conf from fftw 3.3.10.
   DO NOT EDIT!  (Unless you really, really want to.  Then it's okay.) */
void fftw_configure_planner(void *plnr)
{
    struct solvtab_s { void (*reg)(void *); const char *reg_nam; };
    extern void fftw_solvtab_exec(const struct solvtab_s s[], void *);

#define DO(X) \
    X(fftw_codelet_n1_64)\
    X(fftw_codelet_t1_32)\
    /* end DO(X) */

    DO(DECLARE)

    const struct solvtab_s s[] = {
        DO(SOLVTAB)
        { 0, 0 }
    };

    fftw_solvtab_exec(s, plnr);
#undef DO
}
